### ISSUE TITLE
choose options - replicated twice

### ISSUE THREAD

**Issue by VikramTiwari** [googlecodelabs/cloud-vision#1]
![screen shot 2016-07-17 at 12 04 16 pm](https://cloud.githubusercontent.com/assets/1330677/16902540/aad141d4-4c16-11e6-8649-2bfed0c23ee7.png)

URL: https://codelabs.developers.google.com/codelabs/cloud-vision-nodejs/index.html?index=..%2F..%2Findex#0

**Comment by x1ddos** [comment]
This is now fixed. Thanks for reporting.
